### ISSUE TITLE
com.azeesoft.lib.colorpicker.SatValPicker.refreshSatValPicker

### ISSUE THREAD

**Issue by vishrut2207** [AzeeSoft/AndroidPhotoshopColorPicker#5]
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@c620e20 rejected from java.util.concurrent.ThreadPoolExecutor@32cdf3d9[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 125]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:594)
       at com.azeesoft.lib.colorpicker.SatValPicker.refreshSatValPicker(SourceFile:279)
       at com.azeesoft.lib.colorpicker.ColorPickerDialog$3.onPicked(SourceFile:236)
       at com.azeesoft.lib.colorpicker.HuePicker.setHue(SourceFile:85)
       at com.azeesoft.lib.colorpicker.HuePicker$2.onProgressChanged(SourceFile:65)
       at android.widget.SeekBar.onProgressRefresh(SeekBar.java:95)
       at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1353)
       at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1369)
       at android.widget.ProgressBar.setProgress(ProgressBar.java:1416)
       at android.widget.AbsSeekBar.setProgress(AbsSeekBar.java:1063)
       at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:965)
       at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:865)
       at com.azeesoft.lib.colorpicker.OrientedSeekBar.onTouchEvent(SourceFile:101)
       at android.view.View.dispatchTouchEvent(View.java:9144)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2687)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2362)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2687)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2362)
       at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:615)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2687)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2362)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2687)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2362)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2687)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2362)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2687)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2362)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2739)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1832)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:956)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2700)
       at android.view.View.dispatchPointerEvent(View.java:9354)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4976)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4737)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4269)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4322)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4288)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4414)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4296)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4471)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4269)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4322)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4288)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4296)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4269)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6866)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6747)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6718)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6956)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6927)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6979)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:558)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6862)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by axitasavani** [comment]
yes, I have the same issue . 

```
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@a5209b7 rejected from java.util.concurrent.ThreadPoolExecutor@e6e1524[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 240]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2049)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:814)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1360)
       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:616)
       at com.azeesoft.lib.colorpicker.SatValPicker.refreshSatValPicker(SatValPicker.java:279)
       at com.azeesoft.lib.colorpicker.ColorPickerDialog$3.onPicked(ColorPickerDialog.java:236)
       at com.azeesoft.lib.colorpicker.HuePicker.setHue(HuePicker.java:85)
       at com.azeesoft.lib.colorpicker.HuePicker$2.onProgressChanged(HuePicker.java:65)
       at android.widget.SeekBar.onProgressRefresh(SeekBar.java:93)
       at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1337)
       at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1392)
       at android.widget.ProgressBar.setProgressInternal(ProgressBar.java:1462)
       at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:855)
       at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:765)
       at com.azeesoft.lib.colorpicker.OrientedSeekBar.onTouchEvent(OrientedSeekBar.java:101)
       at android.view.View.dispatchTouchEvent(View.java:10062)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:435)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:803)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
       at android.view.View.dispatchPointerEvent(View.java:10293)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4928)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4787)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4459)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4516)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6817)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6791)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6734)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6989)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6948)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7015)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:907)
       at android.view.Choreographer.doCallbacks(Choreographer.java:709)
       at android.view.Choreographer.doFrame(Choreographer.java:638)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
       at android.os.Handler.handleCallback(Handler.java:836)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6253)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

please Give Solution.
